### ISSUE TITLE
src/metrics: Support sub-registry by label

### ISSUE THREAD

**Issue by mxinden** [mxinden/rust-open-metrics-client#13]
Today, one can create a sub-registry with a metric name prefix:

https://github.com/mxinden/rust-open-metrics-client/blob/245cd2f74492e99840119fb11c2b4b82ba95f2d9/src/registry.rs#L158-L189

We should support creating sub-registries either by metric name or constant label(s).

**Comment by hdost** [comment]
Looks like this was completed in #20

**Comment by mxinden** [comment]
Indeed. Thanks @hdost!
