### ISSUE TITLE
How to feed to prometheus?

### ISSUE THREAD

**Issue by divagant-martian** [mxinden/rust-open-metrics-client#22]
Looking for some advice on feeding the metrics stored in a `Registry` to a prometheus instance, using https://crates.io/crates/prometheus. I could add an example to the repo after I get it working.

Thanks!

**Comment by mxinden** [comment]
There is no way to convert a `open-metrics-client` `Registry` to a `prometheus` `Registry`. Neither of them were designed to be converted to the other.

I am guessing that you are using both and now want to expose their metrics on the same http endpoint, correct? I would suggest simply concatenating their text output and returning the sum to each Prometheus server scrape request. Does that work for you?

(There might be some edge cases, as the `prometheus` crate still uses the old Prometheus output format, whereas `open-metrics-client` uses the new OpenMetrics output format.)
